export default {
    value: 'DATA_3001_PERSON_A80',
    text: '处分',
    ledgerChildField: 'A8001',
    childTabItemID: 'A8001',
    childTabCodeID: 'BB015',
    LedgerDateOrderItemID: 'A8005',
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 50,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '身份证号',
            field: 'A0184',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            coldataAlign: 'left',
            align: 'center',
            ItemType: 'S',
        },
        {
            text: '人员类别',
            field: 'A0160',
            dbfield: true,
            width: 100,
            SetID: 'A01',
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '政纪处分',
            field: 'A8001',
            dbfield: true,
            width: 100,
            SetID: 'BBP09',
            IsEdit: true,
            isFilter: true,
            ItemType: 'C',
            CodeID: 'BB015',
        },
        {
            text: '批准时间',
            field: 'A8005',
            dbfield: true,
            width: 100,
            SetID: 'BBP09',
            IsEdit: true,
            ItemType: 'D',
            isOrder: true,
        },
        {
            text: '处分时职务层次',
            field: 'A8002',
            dbfield: true,
            width: 150,
            SetID: 'BBP09',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
            CodeID: 'BB003',
        },
    ],
};
