export default {
    value: 'DATA_3001_PERSON_A73',
    text: '减少',
    childTabItemID: 'A7301', // 筛选条件代码项字段
    childTabCodeID: 'BB005', // 筛选条件代码项
    LedgerDateOrderItemID: 'A7303', // 筛选条件时间排序字段
    childTabs: [],
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 80,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 300,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '出生年月',
            field: 'A0107',
            dbfield: true,
            width: 150,
            SetID: 'A01',
            isFixed: true,
            ItemType: 'D',
            IsTimeItem: true,
        },
        {
            text: '身份证号',
            field: 'A0177',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '性别',
            field: 'A0104',
            dbfield: true,
            width: 80,
            CodeID: 'GB/T2261.1',
            isFilter: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '民族',
            field: 'A0117',
            dbfield: true,
            width: 80,
            SetID: 'A01',
            CodeID: 'GB3304',
            ItemType: 'C',
            isFilter: true,
        },
        {
            text: '减少方式',
            field: 'A7301',
            dbfield: true,
            width: 100,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'BB005',
        },
        {
            text: '调往何处',
            field: 'A7308',
            dbfield: true,
            width: 100,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'BB017',
        },
        {
            text: '调往单位',
            field: 'A7307',
            dbfield: true,
            width: 100,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'S',
        },
        {
            text: '减少时间',
            field: 'A7303',
            dbfield: true,
            width: 100,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'D',
            IsTimeItem: true,
            isOrder: true,
        },
        {
            text: '减少时人员类别',
            field: 'A7302',
            dbfield: true,
            width: 120,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '原工作单位及职务',
            field: 'A0192A',
            dbfield: true,
            width: 300,
            isFixed: false,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '减少时职务层次',
            field: 'A7304',
            dbfield: true,
            width: 120,
            SetID: 'A73',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'BB003',
        },
    ],
};
