export default {
    value: 'DATA_3001_PERSON_A81',
    text: '申诉',
    ledgerChildField: 'A8103',
    childTabItemID: 'A8103',
    childTabCodeID: 'BB016',
    LedgerDateOrderItemID: 'A8107',
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 50,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '身份证号',
            field: 'A0184',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '人员类别',
            field: 'A0160',
            dbfield: true,
            width: 100,
            SetID: 'A01',
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '是否提出申诉',
            field: 'A8101',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            IsEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'XZ04',
        },
        {
            text: '是否受理申诉',
            field: 'A8102',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
            CodeID: 'XZ04',
        },
        {
            text: '申诉处理决定',
            field: 'A8103',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
            CodeID: 'BB016',
        },
        {
            text: '是否提出再申诉',
            field: 'A8104',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
            CodeID: 'XZ04',
        },
        {
            text: '是否受理再申诉',
            field: 'A8105',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
            CodeID: 'XZ04',
        },
        {
            text: '再申诉处理决定',
            field: 'A8106',
            dbfield: true,
            width: 120,
            SetID: 'BBP09',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB016',
        },
        {
            text: '提出申诉时职务层次',
            field: 'A8107',
            dbfield: true,
            width: 100,
            SetID: 'BBP09',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB003',
        },
    ],
};
