export default {
    value: 'DATA_3001_PERSON_A83',
    text: '领导职务试用',
    ledgerChildField: '',
    childTabItemID: 'A8301',
    childTabCodeID: 'BB003',
    LedgerDateOrderItemID: '',
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 50,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '身份证号',
            field: 'A0184',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '人员类别',
            field: 'A0160',
            dbfield: true,
            width: 100,
            SetID: 'A01',
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '领导职务试用期间职务层次',
            field: 'A8301',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB003',
        },
        {
            text: '目前正处于试用期情况',
            field: 'A8302',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB018',
        },
        {
            text: '本年度内试用期满转正情况',
            field: 'A8303',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB022',
        },
        {
            text: '本年度内试用期间调整岗位情况',
            field: 'A8304',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB023',
        },
        {
            text: '本年度内取消试用情况',
            field: 'A8305',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB024',
        },
        {
            text: '取消试用后职务安排',
            field: 'A8306',
            dbfield: true,
            width: 200,
            SetID: 'A83',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB019',
        },
    ],
};
