// 津补贴信息;
export const JBT_TABLE = [
    {
        TABLE_COLUMN_CODE: 'GZDA07C52',
        TABLE_COLUMN_NAME: '乡村教师补贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 1,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C53',
        TABLE_COLUMN_NAME: '绩效工资',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 1,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C54',
        TABLE_COLUMN_NAME: '奖励性绩效工资',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 1,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07B01',
        TABLE_COLUMN_NAME: '艰苦边远地区津贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ40',
        SHOW_TABLE_TYPE: 'double',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07B03',
        TABLE_COLUMN_NAME: '中小学非教10%补贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ13',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07B05',
        TABLE_COLUMN_NAME: '驾驶员津贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07B06',
        TABLE_COLUMN_NAME: '特教津贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07D07',
        TABLE_COLUMN_NAME: '军队服务津贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C61',
        TABLE_COLUMN_NAME: '高海拔地区折算工龄补贴',
        TABLE_COLUMN_TYPE: 3,
        IS_SHOW_TYPE: 0,
        SON_TABLE_FIELD: 'GZ54',
        SHOW_TABLE_TYPE: 'double',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C01',
        TABLE_COLUMN_NAME: '保留补贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C02',
        TABLE_COLUMN_NAME: '老粮贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },

    {
        TABLE_COLUMN_CODE: 'GZDA07C03',
        TABLE_COLUMN_NAME: '回族伙食补贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },

    {
        TABLE_COLUMN_CODE: 'GZDA07C04',
        TABLE_COLUMN_NAME: '岗位津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C10',
        TABLE_COLUMN_NAME: '中小学班主任津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C11',
        TABLE_COLUMN_NAME: '中小学特级教师津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C23',
        TABLE_COLUMN_NAME: '教师护士保留10%',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C29',
        TABLE_COLUMN_NAME: '医疗卫生津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C30',
        TABLE_COLUMN_NAME: '卫生防疫津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07C34',
        TABLE_COLUMN_NAME: '农、林业有毒有害津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07D06',
        TABLE_COLUMN_NAME: '教护龄津贴',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
    {
        TABLE_COLUMN_CODE: 'GZDA07D15',
        TABLE_COLUMN_NAME: '独生子女费',
        TABLE_COLUMN_TYPE: 3,
        SON_TABLE_FIELD: 'GZ21A',
    },
];
