export default {
    value: 'DATA_3001_TEAM_BZ08',
    text: '街道班子',
    childTabItemID: '', // 筛选条件代码项字段
    childTabCodeID: '', // 筛选条件代码项
    LedgerDateOrderItemID: '', // 筛选条件时间排序字段
    A0101ItemID: 'BZ0101', // 姓名筛选字段名
    tblCols: [
        {
            text: '序号',
            field: 'Row_Number',
            dbfield: true,
            width: 50,
            isFixed: true,
            SetID: 'BZ08',
            ItemType: 'S',
        },
        {
            text: '统计单位',
            field: 'BZ08A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'BZ08',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'BZ0801',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'BZ08',
            ItemType: 'S',
            IsEdit: true,
        },
        {
            text: '身份证号',
            field: 'BZ0802',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'BZ08',
            ItemType: 'S',
            IsEdit: true,
        },
        {
            text: '性别',
            field: 'BZ0803',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'BZ08',
            CodeID: 'GB/T2261.1',
            ItemType: 'C',
            IsEdit: true,
        },
        {
            text: '民族',
            field: 'BZ0804',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            CodeID: 'GB3304',
            ItemType: 'C',
            IsEdit: true,
        },
        {
            text: '出生年月',
            field: 'BZ0805',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            ItemType: 'D',
            IsTimeItem: true,
            IsEdit: true,
        },
        {
            text: '参加工作时间',
            field: 'BZ0806',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            ItemType: 'D',
            IsTimeItem: true,
            IsEdit: true,
        },
        {
            text: '政治面貌',
            field: 'BZ0807',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            CodeID: 'GB4762',
            ItemType: 'C',
            IsEdit: true,
        },
        {
            text: '入党时间',
            field: 'BZ0808',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            IsEdit: true,
            ItemType: 'D',
            isOrder: true,
            IsTimeItem: true,
        },
        {
            text: '全日制学历',
            field: 'BZ0809',
            dbfield: true,
            width: 150,
            SetID: 'BZ08',
            CodeID: 'GB4658',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
        },
        {
            text: '最高学历',
            field: 'BZ0810',
            dbfield: true,
            width: 150,
            SetID: 'BZ08',
            CodeID: 'GB4658',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
        },
        {
            text: '最高学位',
            field: 'BZ0811',
            dbfield: true,
            width: 150,
            SetID: 'BZ08',
            IsEdit: true,
            ItemType: 'C',
            CodeID: 'GB/T6864',
        },
        {
            text: '党委职务类别',
            field: 'BZ0812',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            CodeID: 'BB038',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
        },
        {
            text: '政府职务类别',
            field: 'BZ0813',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            CodeID: 'BB039',
            ItemType: 'C',
            IsEdit: true,
            isFilter: true,
        },
        {
            text: '任现职务时间',
            field: 'BZ0814',
            dbfield: true,
            width: 100,
            SetID: 'BZ08',
            ItemType: 'D',
            IsEdit: true,
            IsTimeItem: true,
            isOrder: true,
        },
        {
            text: '任现职务职级层次时间',
            field: 'BZ0815',
            dbfield: true,
            width: 200,
            SetID: 'BZ08',
            ItemType: 'D',
            IsEdit: true,
            IsTimeItem: true,
            isOrder: true,
        },
    ],
};
