export default {
    value: 'DATA_3001_PERSON_A75',
    text: '交流',
    ledgerChildField: 'A7512',
    childTabItemID: 'A7512', // 筛选条件代码项字段
    childTabCodeID: 'BB007', // 筛选条件代码项
    LedgerDateOrderItemID: 'A7501', // 筛选条件时间排序字段
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 80,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '出生年月',
            field: 'A0107',
            dbfield: true,
            width: 150,
            SetID: 'A01',
            isFixed: true,
            ItemType: 'D',
            IsTimeItem: true,
        },
        {
            text: '身份证号',
            field: 'A0177',
            dbfield: true,
            width: 150,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '性别',
            field: 'A0104',
            dbfield: true,
            width: 80,
            CodeID: 'GB/T2261.1',
            isFilter: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '民族',
            field: 'A0117',
            dbfield: true,
            width: 80,
            SetID: 'A01',
            CodeID: 'GB3304',
            ItemType: 'C',
            isFilter: true,
        },
        {
            text: '交流时间',
            field: 'A7501',
            dbfield: true,
            width: 100,
            SetID: 'A75',
            isOrder: true,
            isEdit: true,
            ItemType: 'D',
            IsTimeItem: true,
        },
        {
            text: '交流形式',
            field: 'A7512',
            dbfield: true,
            width: 100,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'BB007',
        },
        {
            text: '交流去向',
            field: 'A7513',
            dbfield: true,
            width: 100,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'BB008',
        },
        {
            text: '交流时人员类别',
            field: 'A7502',
            dbfield: true,
            width: 120,
            SetID: 'A75',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '交流时年龄',
            field: 'A7503',
            dbfield: true,
            width: 100,
            SetID: 'A75',
            isEdit: true,
            ItemType: 'N',
            isOrder: true,
        },
        {
            text: '交流时政治面貌',
            field: 'A7504',
            dbfield: true,
            width: 120,
            SetID: 'A75',
            isEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'GB4762',
        },
        {
            text: '交流时全日制最高学历',
            field: 'A7505',
            dbfield: true,
            width: 200,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            CodeID: 'GB4658',
            isFilter: true,
            isOrder: true,
        },
        {
            text: '交流时最高学历',
            field: 'A7506',
            dbfield: true,
            width: 200,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'GB4658',
            isOrder: true,
        },
        {
            text: '交流时职务层次',
            field: 'A7507',
            dbfield: true,
            width: 200,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'BB003',
        },
        {
            text: '是否任现职满10年交流',
            field: 'A7510',
            dbfield: true,
            width: 200,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'XZ04',
        },
        {
            text: '是否回避交流',
            field: 'A7511',
            dbfield: true,
            width: 100,
            SetID: 'A75',
            ItemType: 'C',
            isEdit: true,
            isFilter: true,
            CodeID: 'XZ04',
        },
    ],
};
