export default {
    value: 'DATA_3001_PERSON_A78',
    text: '免、降、辞去领导',
    ledgerChildField: 'A7801',
    childTabItemID: 'A7801',
    childTabCodeID: 'BB013',
    LedgerDateOrderItemID: 'A7805',
    tblCols: [
        {
            text: '序号',
            field: 'ROWNUM_',
            dbfield: true,
            width: 50,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'N',
        },
        {
            text: '单位',
            field: 'A0195',
            dbfield: true,
            width: 220,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'C',
        },
        {
            text: '姓名',
            field: 'A0101',
            dbfield: true,
            width: 100,
            isFixed: true,
            SetID: 'A01',
            ItemType: 'S',
        },
        {
            text: '身份证号',
            field: 'A0184',
            dbfield: true,
            isFixed: true,
            SetID: 'A01',
            width: 150,
            coldataAlign: 'center',
            align: 'center',
            ItemType: 'S',
        },
        {
            text: '人员类别',
            field: 'A0160',
            dbfield: true,
            width: 100,
            SetID: 'A01',
            ItemType: 'C',
            isFilter: true,
            CodeID: 'STATUS',
        },
        {
            text: '情况类别',
            field: 'A7801',
            dbfield: true,
            width: 100,
            SetID: 'A78',
            IsEdit: true,
            ItemType: 'C',
            isFilter: true,
            CodeID: 'BB013',
        },
        {
            text: '批准时间',
            field: 'A7805',
            dbfield: true,
            width: 100,
            SetID: 'A78',
            IsEdit: true,
            ItemType: 'D',
            isOrder: true,
        },
        {
            text: '职务层次',
            field: 'A7802',
            dbfield: true,
            width: 200,
            SetID: 'A78',
            ItemType: 'C',
            isFilter: true,
            IsEdit: true,
            CodeID: 'BB003',
        },
    ],
};
